#!/usr/bin/env node
/**
 * Generate local + deploy env files with random secrets.
 * Safe to re-run; skips files that already exist unless --force.
 *
 * Usage:
 *   node scripts/generate-env.mjs
 *   node scripts/generate-env.mjs --force
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, '..');
const force = process.argv.includes('--force');

function secret(bytes = 32) {
  return crypto.randomBytes(bytes).toString('base64url');
}

function writeIfMissing(filePath, content) {
  if (!force && fs.existsSync(filePath)) {
    console.log(`skip (exists): ${path.relative(root, filePath)}`);
    return false;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`written: ${path.relative(root, filePath)}`);
  return true;
}

const sessionSecret = secret(32);
const serverToken = secret(24);
const dbPassword = secret(18);

const rootEnv = `# Generated by scripts/generate-env.mjs — local API + Vite dev
PORT=3000
NODE_ENV=development

SESSION_SECRET=${sessionSecret}
SERVER_TOKEN=${serverToken}

DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=matchzy_tournament

ORGANIZATION_ID=fragbase
ORGANIZATION_NAME=Fragbase Local
ORGANIZATION_SLUG=fragbase

# Org portal (Vite 5174) — OAuth redirects
FRONTEND_BASE_URL=http://localhost:5174
API_BASE_URL=http://localhost:3000
PLAYER_PORTAL_URL=http://localhost:5173

PLAYER_HOST=play.localhost
ORG_HOST=admin.localhost

AUTH_STEAM_ENABLED=true
STEAM_API_KEY=

LOG_LEVEL=info

# Mercado Pago (fill when testing payments)
MERCADOPAGO_CLIENT_ID=
MERCADOPAGO_CLIENT_SECRET=
MERCADOPAGO_REDIRECT_URI=http://localhost:5174/api/payments/mercadopago/callback
`;

const localOrgEnv = `# Generated — local Docker org stack (scripts/org-stack.sh local-org up)
ORG_SLUG=local-org
ORGANIZATION_NAME=Fragbase Local Org
ORGANIZATION_SLUG=local-org
HOST_PORT=3070

FRONTEND_BASE_URL=http://localhost:3070
API_BASE_URL=http://localhost:3070
PLAYER_PORTAL_URL=http://localhost:5173

ORG_HOST=admin.localhost
PLAYER_HOST=play.localhost

DB_USER=postgres
DB_PASSWORD=${dbPassword}
DB_NAME=matchzy_tournament

SESSION_SECRET=${sessionSecret}
SERVER_TOKEN=${serverToken}

STEAM_API_KEY=

MERCADOPAGO_CLIENT_ID=
MERCADOPAGO_CLIENT_SECRET=
MERCADOPAGO_REDIRECT_URI=http://localhost:3070/api/payments/mercadopago/callback
`;

const localHubEnv = `# Generated — local Docker hub stack (scripts/hub-stack.sh up)
HOST_PORT=3068

ORGANIZATION_ID=hub
ORGANIZATION_NAME=Fragbase Hub Local
ORGANIZATION_SLUG=hub

FRONTEND_BASE_URL=http://localhost:3068
API_BASE_URL=http://localhost:3068
PLAYER_PORTAL_URL=http://localhost:3068

PLAYER_HOST=play.localhost
ORG_HOST=admin.localhost

DB_USER=postgres
DB_PASSWORD=${dbPassword}
DB_NAME=fragbase_hub

SESSION_SECRET=${sessionSecret}
SERVER_TOKEN=${serverToken}

STEAM_API_KEY=
`;

const fragbaseCampEnv = `# Generated — production template for first camp (edit domains before deploy)
ORG_SLUG=fragbase-camp
ORGANIZATION_NAME=Fragbase Camp
ORGANIZATION_SLUG=fragbase-camp
HOST_PORT=3069

FRONTEND_BASE_URL=https://admin.fragbase.gg
API_BASE_URL=https://admin.fragbase.gg
PLAYER_PORTAL_URL=https://play.fragbase.gg

ORG_HOST=admin.fragbase.gg
PLAYER_HOST=play.fragbase.gg

DB_USER=postgres
DB_PASSWORD=${dbPassword}
DB_NAME=matchzy_tournament

SESSION_SECRET=${sessionSecret}
SERVER_TOKEN=${serverToken}

STEAM_API_KEY=your-steam-web-api-key

MERCADOPAGO_CLIENT_ID=
MERCADOPAGO_CLIENT_SECRET=
MERCADOPAGO_REDIRECT_URI=https://admin.fragbase.gg/api/payments/mercadopago/callback
`;

writeIfMissing(path.join(root, '.env'), rootEnv);
writeIfMissing(path.join(root, 'docker/env/local-org.env'), localOrgEnv);
writeIfMissing(path.join(root, 'docker/env/local-hub.env'), localHubEnv);
writeIfMissing(path.join(root, 'docker/env/fragbase-camp.env'), fragbaseCampEnv);

console.log('\nDone. Add STEAM_API_KEY to .env before Steam login works.');
console.log('Dev: yarn db && yarn dev:player / yarn dev:org');
