#!/usr/bin/env node
/**
 * Generate local + deploy env files with random secrets.
 * Safe to re-run; skips files that already exist unless --force.
 *
 * Usage:
 *   node scripts/generate-env.mjs
 *   node scripts/generate-env.mjs --force
 *
 * After generate, you only need to fill STEAM_API_KEY (and domains on prod).
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, '..');
const force = process.argv.includes('--force');

function secret(bytes = 32) {
  return crypto.randomBytes(bytes).toString('base64url');
}

function writeIfMissing(filePath, content) {
  if (!force && fs.existsSync(filePath)) {
    console.log(`skip (exists): ${path.relative(root, filePath)}`);
    return false;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`written: ${path.relative(root, filePath)}`);
  return true;
}

const sessionSecret = secret(32);
const serverToken = secret(24);
const dbPassword = secret(18);

/** Shared header for docker org/hub env files */
function envHeader(title, slug) {
  return `############################################################
# ${title}
# Generated by scripts/generate-env.mjs
#
# MANUAL (required for prod):
#   STEAM_API_KEY=https://steamcommunity.com/dev/apikey
#   Edit domains below if your DNS differs
#   MERCADOPAGO_* if tournament registration fee > 0
#
# Secrets below are random — keep them if this file already exists.
############################################################
`;
}

/**
 * Per-org Docker stack env (see docker/docker-compose.org.yml).
 * ORGANIZATION_ID is also injected from ORG_SLUG in compose — keep them aligned.
 */
function orgStackEnv({
  slug,
  orgName,
  hostPort,
  adminBaseUrl,
  playBaseUrl,
  orgHost,
  playerHost,
  dbName = 'matchzy_tournament',
  dbPass,
  sess,
  srvToken,
  steamKey = '',
}) {
  const admin = adminBaseUrl.replace(/\/+$/, '');
  const play = playBaseUrl.replace(/\/+$/, '');
  return `${envHeader(`Fragbase org stack — ${slug}`, slug)}
##############################
# Stack identity
##############################
ORG_SLUG=${slug}
ORGANIZATION_ID=${slug}
ORGANIZATION_NAME=${orgName}
ORGANIZATION_SLUG=${slug}
HOST_PORT=${hostPort}

##############################
# Public URLs (OAuth, MP webhook, checkout returns)
# FRONTEND_BASE_URL = org admin portal (OAuth redirects)
# API_BASE_URL = public API (CS2 webhooks, Mercado Pago)
# PLAYER_PORTAL_URL = player browse/checkout return URLs
##############################
FRONTEND_BASE_URL=${admin}
API_BASE_URL=${admin}
PLAYER_PORTAL_URL=${play}

##############################
# Caddy vhosts inside container (must match DNS / tunnel)
##############################
ORG_HOST=${orgHost}
PLAYER_HOST=${playerHost}

##############################
# Database (isolated Postgres in this stack)
##############################
DB_USER=postgres
DB_PASSWORD=${dbPass}
DB_NAME=${dbName}
# DATABASE_URL is set by docker-compose — only override for custom setups

##############################
# Runtime
##############################
NODE_ENV=production
PORT=3000
SESSION_SECRET=${sess}
SERVER_TOKEN=${srvToken}

##############################
# Auth (Steam required for login)
##############################
AUTH_STEAM_ENABLED=true
STEAM_API_KEY=${steamKey}

# Optional SSO (uncomment + fill; redirect = FRONTEND_BASE_URL + /api/auth/.../callback)
# AUTH_DISCORD_ENABLED=true
# DISCORD_CLIENT_ID=
# DISCORD_CLIENT_SECRET=
# AUTH_GITHUB_ENABLED=true
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# AUTH_KEYCLOAK_ENABLED=true
# KEYCLOAK_ISSUER_URL=
# KEYCLOAK_CLIENT_ID=
# KEYCLOAK_CLIENT_SECRET=

##############################
# Mercado Pago (org checkout — skip if registration is free)
# Redirect URI must match MP app + API_BASE_URL
##############################
MERCADOPAGO_CLIENT_ID=
MERCADOPAGO_CLIENT_SECRET=
MERCADOPAGO_REDIRECT_URI=${admin}/api/payments/mercadopago/callback

##############################
# Docker image & logging
##############################
# MAT_IMAGE=sivertio/matchzy-auto-tournament:latest
LOG_LEVEL=info
# LOG_HTTP_REQUESTS=true
# CORS_ORIGIN=*

##############################
# Optional integrations
##############################
# FACEIT_API_KEY=
# CS2_ADMINS_JSON_PATH=
# MATCHZY_ENABLE_SIMULATION_IN_PROD=false
`;
}

const rootEnv = `# Generated by scripts/generate-env.mjs — local API + Vite dev portals
#
# Fill STEAM_API_KEY before Steam login works.
# Player: yarn dev:player:win → http://localhost:5173
# Org:    yarn dev:org:win    → http://localhost:5174

##############################
# API server
##############################
PORT=3000
NODE_ENV=development
SESSION_SECRET=${sessionSecret}
SERVER_TOKEN=${serverToken}

##############################
# Database (yarn db → Postgres on 5432)
##############################
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=matchzy_tournament

##############################
# Instance org (local single-org)
##############################
ORGANIZATION_ID=fragbase
ORGANIZATION_NAME=Fragbase Local
ORGANIZATION_SLUG=fragbase

##############################
# URLs — split dev portals
# FRONTEND_BASE_URL = org portal (OAuth redirects)
# API_BASE_URL = API (webhooks, Mercado Pago)
# PLAYER_PORTAL_URL = player portal (checkout returns)
##############################
FRONTEND_BASE_URL=http://localhost:5174
API_BASE_URL=http://localhost:3000
PLAYER_PORTAL_URL=http://localhost:5173

PLAYER_HOST=play.localhost
ORG_HOST=admin.localhost

##############################
# Auth
##############################
AUTH_STEAM_ENABLED=true
STEAM_API_KEY=

##############################
# Mercado Pago (API callback on :3000, not Vite)
##############################
MERCADOPAGO_CLIENT_ID=
MERCADOPAGO_CLIENT_SECRET=
MERCADOPAGO_REDIRECT_URI=http://localhost:3000/api/payments/mercadopago/callback

##############################
# Logging
##############################
LOG_LEVEL=info
`;

const localOrgEnv = orgStackEnv({
  slug: 'local-org',
  orgName: 'Fragbase Local Org',
  hostPort: 3070,
  adminBaseUrl: 'http://admin.localhost:3070',
  playBaseUrl: 'http://play.localhost:3070',
  orgHost: 'admin.localhost',
  playerHost: 'play.localhost',
  dbPass: dbPassword,
  sess: sessionSecret,
  srvToken: serverToken,
});

const hubEnv = `${envHeader('Fragbase hub stack (play.fragbase.gg)', 'hub')}
HOST_PORT=3068

ORGANIZATION_ID=hub
ORGANIZATION_NAME=Fragbase Hub
ORGANIZATION_SLUG=hub

FRONTEND_BASE_URL=https://play.fragbase.gg
API_BASE_URL=https://play.fragbase.gg
PLAYER_PORTAL_URL=https://play.fragbase.gg

PLAYER_HOST=play.fragbase.gg
ORG_HOST=admin.fragbase.gg

DB_USER=postgres
DB_PASSWORD=${dbPassword}
DB_NAME=fragbase_hub

NODE_ENV=production
PORT=3000
SESSION_SECRET=${sessionSecret}
SERVER_TOKEN=${serverToken}

AUTH_STEAM_ENABLED=true
STEAM_API_KEY=

LOG_LEVEL=info
# MAT_IMAGE=sivertio/matchzy-auto-tournament:latest
`;

const fragbaseCampEnv = orgStackEnv({
  slug: 'fragbase-camp',
  orgName: 'Fragbase Camp',
  hostPort: 3069,
  adminBaseUrl: 'https://admin.fragbase.gg',
  playBaseUrl: 'https://play.fragbase.gg',
  orgHost: 'admin.fragbase.gg',
  playerHost: 'play.fragbase.gg',
  dbPass: dbPassword,
  sess: sessionSecret,
  srvToken: serverToken,
  steamKey: 'your-steam-web-api-key',
});

writeIfMissing(path.join(root, '.env'), rootEnv);
writeIfMissing(path.join(root, 'docker/env/local-org.env'), localOrgEnv);
writeIfMissing(path.join(root, 'docker/env/local-hub.env'), hubEnv);
writeIfMissing(path.join(root, 'docker/env/fragbase-camp.env'), fragbaseCampEnv);

console.log('\nDone.');
console.log('Required: set STEAM_API_KEY in .env (and docker/env/*.env for Docker).');
console.log('Prod: edit domains in docker/env/fragbase-camp.env then ./scripts/org-stack.sh fragbase-camp up');
console.log('Dev:  yarn db && yarn dev:player:win / yarn dev:org:win');
